### ISSUE TITLE
EACirc repos relationship

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/eacirc-core#1]
What is the purpose of eacirc-core repo? Won't the core remain in the original eacirc repository? Please note that removing the original repo would be the most unfortunate, since several publications (and even the DOI EACirc version) link to it.

@xtracko @Bender250 -- who knows the details?

**Comment by ghost** [comment]
We need to create a separate repository for the generator, but we don't want to synchronise core module manually so we need some repository structure. In this repository, there will be the core of eacirc (everything from core module, I believe) then the core will be added to eacirc as a submodule and also to the generator.

**Comment by mukrop** [comment]
Ok, understood. Thanks.

**Comment by xtracko** [comment]
Actually for this purpose we need a better name than core. Basically by
'core' I mean just the common header files in eacirc framework.
